name: Go installation check
on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-latest
      
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">1.0.0"
      - name: RUN Go
        run: go version
